---
- name: Insert ssh public key into CMS
  local_action:
    module             :  cs_sshkeypair
    name               :  sdr-test-ssh-key                    ## inventory_hostname_short is a 'magic variable', hostname up to the first '.'
    public_key         :  "{{ lookup('file', '/home/drose/.ssh/id_rsa.pub') }}"
  register             :  install_sshkey_return

- name: Build VM instance or ensure it is already established.
  local_action:
    module             :  cs_instance
    api_region         :  "{{ api_region }}"                  ## This is in the ./cloudstack.ini file.
    zone               :  "{{ cs_zone }}"                     ## Specifying the zone is REQUIRED when working in a multizone cloud environment.
    name               :  "{{ inventory_hostname_short }}"    ## inventory_hostname_short is a 'magic variable', hostname up to the first '.'
    service_offering   :  "{{ cs_1cpu4gb }}"                
    template           :  "{{ iso_template }}"
    ip_to_networks     :
      - network        :  "{{ network }}"
        ip             :  "{{ private_ip }}"
    ssh_key            :  sdr-test-ssh-key
    state              :  started
  register             :  cs_instance_return

- name                 :  Print cs_instance_return debug info
  debug                :  msg="Password- {{ cs_instance_return.password }}"
  ignore_errors        :  True
  when                 :  cs_instance_return.password is defined

- name: Establish NAT and create ssh portforward to VM ssh port 22.
  local_action:
    module             :  cs_portforward
    api_region         :  "{{ api_region }}"                  ## This is in the ./cloudstack.ini file.
    zone               :  "{{ cs_zone }}"                     ## Specifying the zone is REQUIRED when working in a multizone cloud environment.
    network            :  "{{ network }}"
    ip_address         :  "{{ ansible_host }}"
    vm                 :  "{{ inventory_hostname_short }}"
    public_port        :  "{{ ansible_ssh_port }}"
    private_port       :  22
    protocol           :  tcp
    open_firewall      :  yes
    state              :  present
  register             :  cs_portforward_return

- name                 :  Print cs_portforward_return info
  debug                :  msg="cs_portforward- {{ cs_portforward_return }}"

- name: Create/attach DATA volume to VM instance.
  local_action:
    module             :  cs_volume
    api_region         :  "{{ api_region }}"                  ## This is in the ./cloudstack.ini file.
    zone               :  "{{ cs_zone }}"                     ## Specifying the zone is REQUIRED when working in a multizone cloud environment.
    name               :  "DATA_{{ inventory_hostname_short }}"
    disk_offering      :  Custom
    size               :  20
    vm                 :  "{{ inventory_hostname_short }}"
    state              :  attached
  when: data_drive_size|int > 0
  register             :  cs_volume_return

- name                 :  Print cs_volume_return info
  debug                :  msg="cs_volume_return- {{ cs_volume_return }}"

# Current VM login is root, now create a 'setup' user.
- name: Add user via /etc/passwd with membership to sudo group.
  user: 
    name               :  setup
    shell              :  /bin/bash
    groups             :  sudo
    append             :  yes
    state              :  present
    createhome         :  yes
  become: true
  register: userCreate_return


- name: Test Command Prompt
  command: hostname
  register: command_return

- name                 :  Print command_return info
  debug                :  msg="command return (hostname)- {{ command_return }}"

- name: Test Command Prompt
  command: whoami
  register: command_return

- name                 :  Print cs_volume_return info
  debug                :  msg="command return (whoami)- {{ command_return }}"
