###########################################################################
####
####  registerIso-btcloud.yml
####  
####  to execute:  
####               eval `ssh-agent -s`
####               ssh-add 
####               ssh-add -l
####
####               ansible-playbook -i inventory.yml registerIso-btcloud.yml -u root 
####
####  In ./inventory.yml
####   ansible_user=root
####   ansible_ssh_private_key_file= "/home/drose/.ssh/id_rsa"
####   ansible_ssh_common_args='-o StrictHostKeyChecking=no'


---
- name:  Register an ISO in the BT Cloud.
  hosts:  localhost
  become: no
  gather_facts: no
  vars:
    liverpool           :  GB-LPL-MINI-P-V-A-R-S-001
    nutley              :  US-NEW-NUT-G-V-A-R-S-001
    cs_zone             :  "{{ nutley }}"
    cs_api_region       :  Dave_CMS4                                     ##  This is in the ./cloudstack.ini file.
    cs_hosts            :  localhost                                     ##  This is a label in the inventory
                                                                         ##  file housing the VM hostnames for provisioning  ...
    iso_url             :  'http://75.124.77.62/'                        ##  Either iso_url ends with '/' or iso_filename starts with '/'
    iso_filename        :  'clonezilla-live-20170220-yakkety-amd64.iso'
    iso_registeredName  :  'Clonezilla'
    other_ubuntu_64     :  'Other Ubuntu (64-bit)'
  roles:
  - registerIso


