###########################################################################
####
####  cloudstack_provision.yml
####  
####  to execute:  ansible-playbook cloudstack_provision.yml -u root 
####               SSH Password:  (Password to unlock ~/.ssh/id_rsa
####
####  In ./inventory.yml
####   ansible_user=root
####   ansible_ssh_private_key_file= "/home/drose/.ssh/id_rsa"
####   ansible_ssh_common_args='-o StrictHostKeyChecking=no'

---
- name:  Provision, or ensure as provisioned, VM instances in the BT Cloud.
  hosts:  linux_btcloud
  become: no
  gather_facts: no
  vars:
    liverpool           :  GB-LPL-MINI-P-V-A-R-S-001
    nutley              :  US-NEW-NUT-G-V-A-R-S-001
    cs_api_region       :  Dave_CMS4                        ##  This is in the ./cloudstack.ini file.
    cs_zone             :  "{{ nutley }}"
    network             :  "Default"
    cs_hosts            :  localhost                        ##  This is a label in the inventory
                                                            ##  file housing the VM hostnames for provisioning  ...
    cs_url              :  "http://75.124.77.62/"
    cs_filename         :  ""
    iso_template : "US_UBUNTU_12.04.02_LTS_x64_1.1.0_ESXi" ##  This is a Compute-developed Template
    #iso_template : "CentOS 7.2"                             ##  This is a template with password-script installed


  roles:
  - instantiateLinuxVMs

- name:  Begin the software installation portion on the instantiated Linux VMs
  hosts:  linux_btcloud
  become: yes
  gather_facts: yes
  roles:
  - apt

